services:
  - type: web
    name: kiseki
    runtime: docker
    plan: free
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: DatabaseProvider
        value: postgres
      - key: ConnectionStrings__DefaultConnection
        sync: false
      - key: KISEKI_PASSWORD
        sync: false
