// <auto-generated />
using System;
using Kiseki.Core;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Kiseki.Core.Migrations
{
    [DbContext(typeof(ImmersionDbContext))]
    [Migration("20260813182325_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("Kiseki.Core.Entities.ImmersionLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("CharactersRead")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("MediaWorkId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("TimeSpentSeconds")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("MediaWorkId");

                    b.ToTable("ImmersionLogs");
                });

            modelBuilder.Entity("Kiseki.Core.Entities.MediaWork", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("JitenCharacterCount")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("JitenDeckId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ManualCharacterCountOverride")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("MediaWorks");
                });

            modelBuilder.Entity("Kiseki.Core.Entities.ImmersionLog", b =>
                {
                    b.HasOne("Kiseki.Core.Entities.MediaWork", null)
                        .WithMany("Logs")
                        .HasForeignKey("MediaWorkId");
                });

            modelBuilder.Entity("Kiseki.Core.Entities.MediaWork", b =>
                {
                    b.Navigation("Logs");
                });
#pragma warning restore 612, 618
        }
    }
}
