// <auto-generated />
using System;
using Kiseki.Core;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Kiseki.Core.Migrations
{
    [DbContext(typeof(ImmersionDbContext))]
    [Migration("20260903141537_AddFranchisesSeriesAndJitenSubdeckLinks")]
    partial class AddFranchisesSeriesAndJitenSubdeckLinks
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("Kiseki.Core.Entities.Franchise", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int?>("JitenAnchorDeckId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("JitenAnchorDeckId");

                    b.ToTable("Franchises");
                });

            modelBuilder.Entity("Kiseki.Core.Entities.ImmersionLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("CharactersRead")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("MediaWorkId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("TimeSpentMinutes")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("MediaWorkId");

                    b.ToTable("ImmersionLogs");
                });

            modelBuilder.Entity("Kiseki.Core.Entities.MediaSeries", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("FranchiseId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("JitenDeckId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MediaType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FranchiseId");

                    b.HasIndex("JitenDeckId");

                    b.ToTable("MediaSeries");
                });

            modelBuilder.Entity("Kiseki.Core.Entities.MediaWork", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("JitenCharacterCount")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("JitenDeckId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("JitenSubdeckId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ManualCharacterCountOverride")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("MediaSeriesId")
                        .HasColumnType("TEXT");

                    b.Property<int>("MediaType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("JitenDeckId");

                    b.HasIndex("JitenSubdeckId");

                    b.HasIndex("MediaSeriesId");

                    b.ToTable("MediaWorks", t =>
                        {
                            t.HasCheckConstraint("CK_MediaWorks_JitenSubdeckRequiresDeck", "JitenSubdeckId IS NULL OR JitenDeckId IS NOT NULL");
                        });
                });

            modelBuilder.Entity("Kiseki.Core.Entities.ImmersionLog", b =>
                {
                    b.HasOne("Kiseki.Core.Entities.MediaWork", null)
                        .WithMany("Logs")
                        .HasForeignKey("MediaWorkId");
                });

            modelBuilder.Entity("Kiseki.Core.Entities.MediaSeries", b =>
                {
                    b.HasOne("Kiseki.Core.Entities.Franchise", "Franchise")
                        .WithMany("Series")
                        .HasForeignKey("FranchiseId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Franchise");
                });

            modelBuilder.Entity("Kiseki.Core.Entities.MediaWork", b =>
                {
                    b.HasOne("Kiseki.Core.Entities.MediaSeries", "MediaSeries")
                        .WithMany("Works")
                        .HasForeignKey("MediaSeriesId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("MediaSeries");
                });

            modelBuilder.Entity("Kiseki.Core.Entities.Franchise", b =>
                {
                    b.Navigation("Series");
                });

            modelBuilder.Entity("Kiseki.Core.Entities.MediaSeries", b =>
                {
                    b.Navigation("Works");
                });

            modelBuilder.Entity("Kiseki.Core.Entities.MediaWork", b =>
                {
                    b.Navigation("Logs");
                });
#pragma warning restore 612, 618
        }
    }
}
