// <auto-generated />
using System;
using Kiseki.Core;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Kiseki.Core.Migrations
{
    [DbContext(typeof(ImmersionDbContext))]
    [Migration("20260922202102_AddJitenCatalogueRefreshState")]
    partial class AddJitenCatalogueRefreshState
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Kiseki.Core.Entities.Franchise", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("JitenAnchorDeckId")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("JitenAnchorDeckId");

                    b.ToTable("Franchises");
                });

            modelBuilder.Entity("Kiseki.Core.Entities.ImmersionLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CharactersRead")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<Guid?>("MediaWorkId")
                        .HasColumnType("uuid");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long?>("SourceRevision")
                        .HasColumnType("bigint");

                    b.Property<double>("TimeSpentMinutes")
                        .HasColumnType("double precision");

                    b.Property<Guid?>("TtsuBindingId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("MediaWorkId");

                    b.HasIndex("TtsuBindingId", "Date")
                        .IsUnique();

                    b.ToTable("ImmersionLogs", t =>
                        {
                            t.HasCheckConstraint("CK_ImmersionLogs_TtsuBinding", "\"TtsuBindingId\" IS NULL OR (\"MediaWorkId\" IS NOT NULL AND \"TtsuBindingId\" = \"MediaWorkId\" AND \"Source\" = 'ttsu')");
                        });
                });

            modelBuilder.Entity("Kiseki.Core.Entities.InstallmentProviderIdentity", b =>
                {
                    b.Property<string>("Provider")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("NormalizedKey")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset?>("LastSeenAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("MediaInstallmentId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("MissingSinceUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ParentProviderItemId")
                        .HasColumnType("integer");

                    b.Property<int>("ProviderItemId")
                        .HasColumnType("integer");

                    b.HasKey("Provider", "NormalizedKey");

                    b.HasIndex("MediaInstallmentId");

                    b.ToTable("InstallmentProviderIdentities", t =>
                        {
                            t.HasCheckConstraint("CK_InstallmentProviderIdentities_ItemIds", "\"ProviderItemId\" > 0 AND (\"ParentProviderItemId\" IS NULL OR \"ParentProviderItemId\" > 0)");

                            t.HasCheckConstraint("CK_InstallmentProviderIdentities_Keys", "length(trim(\"Provider\")) BETWEEN 1 AND 64 AND length(trim(\"NormalizedKey\")) BETWEEN 1 AND 256");
                        });
                });

            modelBuilder.Entity("Kiseki.Core.Entities.InstallmentProviderSnapshot", b =>
                {
                    b.Property<string>("Provider")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("NormalizedKey")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Fingerprint")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int?>("CharacterCount")
                        .HasColumnType("integer");

                    b.Property<int>("CoverSource")
                        .HasColumnType("integer");

                    b.Property<string>("CoverUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<bool>("IsComplete")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("ObservedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PayloadJson")
                        .HasColumnType("text");

                    b.Property<int?>("ProviderOrder")
                        .HasColumnType("integer");

                    b.Property<DateOnly?>("ReleaseDate")
                        .HasColumnType("date");

                    b.Property<int>("ReleaseState")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<Guid>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValue(new Guid("00000000-0000-0000-0000-000000000000"));

                    b.HasKey("Provider", "NormalizedKey", "Fingerprint");

                    b.HasIndex("Provider", "NormalizedKey", "ObservedAtUtc");

                    b.ToTable("InstallmentProviderSnapshots", t =>
                        {
                            t.HasCheckConstraint("CK_InstallmentProviderSnapshots_CharacterCount", "\"CharacterCount\" IS NULL OR \"CharacterCount\" >= 0");

                            t.HasCheckConstraint("CK_InstallmentProviderSnapshots_Cover", "(\"CoverUrl\" IS NULL AND \"CoverSource\" = 0) OR (\"CoverUrl\" IS NOT NULL AND \"CoverSource\" <> 0)");

                            t.HasCheckConstraint("CK_InstallmentProviderSnapshots_Enums", "\"CoverSource\" BETWEEN 0 AND 3 AND \"ReleaseState\" BETWEEN 0 AND 2");

                            t.HasCheckConstraint("CK_InstallmentProviderSnapshots_Fingerprint", "length(trim(\"Fingerprint\")) BETWEEN 1 AND 128");

                            t.HasCheckConstraint("CK_InstallmentProviderSnapshots_ProviderOrder", "\"ProviderOrder\" IS NULL OR \"ProviderOrder\" >= 0");
                        });
                });

            modelBuilder.Entity("Kiseki.Core.Entities.JitenCatalogueRefreshReceipt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AddedInstallments")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Ignored")
                        .HasColumnType("integer");

                    b.Property<int>("JitenDeckId")
                        .HasColumnType("integer");

                    b.Property<int>("LinkedIdentities")
                        .HasColumnType("integer");

                    b.Property<int>("MarkedMissing")
                        .HasColumnType("integer");

                    b.Property<Guid>("MediaSeriesId")
                        .HasColumnType("uuid");

                    b.Property<string>("ReviewFingerprint")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("UpdatedInstallments")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MediaSeriesId");

                    b.ToTable("JitenCatalogueRefreshReceipts", t =>
                        {
                            t.HasCheckConstraint("CK_JitenCatalogueRefreshReceipts_Deck", "\"JitenDeckId\" > 0");

                            t.HasCheckConstraint("CK_JitenCatalogueRefreshReceipts_Fingerprint", "length(trim(\"ReviewFingerprint\")) BETWEEN 1 AND 128");
                        });
                });

            modelBuilder.Entity("Kiseki.Core.Entities.MediaInstallment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("CanonicalCharacterCount")
                        .HasColumnType("integer");

                    b.Property<int>("CanonicalCoverSource")
                        .HasColumnType("integer");

                    b.Property<string>("CanonicalCoverUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("CanonicalTitle")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<int?>("CharacterCountOverride")
                        .HasColumnType("integer");

                    b.Property<bool>("IsIncluded")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<int>("Kind")
                        .HasColumnType("integer");

                    b.Property<string>("LegacyTitle")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<Guid?>("MediaSeriesId")
                        .HasColumnType("uuid");

                    b.Property<int>("MediaType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<int>("OrderKey")
                        .HasColumnType("integer");

                    b.Property<DateOnly?>("ReleaseDate")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("ReleaseDateOverride")
                        .HasColumnType("date");

                    b.Property<int>("ReleaseState")
                        .HasColumnType("integer");

                    b.Property<int?>("ReleaseStateOverride")
                        .HasColumnType("integer");

                    b.Property<string>("TitleOverride")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<Guid>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValue(new Guid("00000000-0000-0000-0000-000000000000"));

                    b.HasKey("Id");

                    b.HasIndex("MediaSeriesId", "OrderKey");

                    b.ToTable("MediaInstallments", t =>
                        {
                            t.HasCheckConstraint("CK_MediaInstallments_CanonicalCharacterCount", "\"CanonicalCharacterCount\" IS NULL OR \"CanonicalCharacterCount\" > 0");

                            t.HasCheckConstraint("CK_MediaInstallments_CanonicalCover", "(\"CanonicalCoverUrl\" IS NULL AND \"CanonicalCoverSource\" = 0) OR (\"CanonicalCoverUrl\" IS NOT NULL AND \"CanonicalCoverSource\" <> 0)");

                            t.HasCheckConstraint("CK_MediaInstallments_CanonicalCoverSource", "\"CanonicalCoverSource\" BETWEEN 0 AND 3");

                            t.HasCheckConstraint("CK_MediaInstallments_CharacterCountOverride", "\"CharacterCountOverride\" IS NULL OR \"CharacterCountOverride\" > 0");

                            t.HasCheckConstraint("CK_MediaInstallments_Kind", "\"Kind\" BETWEEN 0 AND 7");

                            t.HasCheckConstraint("CK_MediaInstallments_MediaType", "\"MediaType\" IN (1, 2, 3)");

                            t.HasCheckConstraint("CK_MediaInstallments_OrderKey", "\"OrderKey\" >= 0");

                            t.HasCheckConstraint("CK_MediaInstallments_ReleaseState", "\"ReleaseState\" BETWEEN 0 AND 2 AND (\"ReleaseStateOverride\" IS NULL OR \"ReleaseStateOverride\" BETWEEN 0 AND 2)");

                            t.HasCheckConstraint("CK_MediaInstallments_Title", "coalesce(length(trim(\"LegacyTitle\")), 0) > 0 OR coalesce(length(trim(\"CanonicalTitle\")), 0) > 0 OR coalesce(length(trim(\"TitleOverride\")), 0) > 0");
                        });
                });

            modelBuilder.Entity("Kiseki.Core.Entities.MediaSeries", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("FranchiseId")
                        .HasColumnType("uuid");

                    b.Property<int?>("JitenDeckId")
                        .HasColumnType("integer");

                    b.Property<int>("MediaType")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FranchiseId");

                    b.HasIndex("JitenDeckId");

                    b.ToTable("MediaSeries");
                });

            modelBuilder.Entity("Kiseki.Core.Entities.MediaWork", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CoverProviderItemId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("CoverSource")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("CoverUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<int?>("JitenCharacterCount")
                        .HasColumnType("integer");

                    b.Property<int?>("JitenDeckId")
                        .HasColumnType("integer");

                    b.Property<int?>("JitenSubdeckId")
                        .HasColumnType("integer");

                    b.Property<int?>("ManualCharacterCountOverride")
                        .HasColumnType("integer");

                    b.Property<Guid?>("MediaInstallmentId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("MediaSeriesId")
                        .HasColumnType("uuid");

                    b.Property<int>("MediaType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("TtsuCharacterCount")
                        .HasColumnType("integer");

                    b.Property<Guid>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValue(new Guid("00000000-0000-0000-0000-000000000000"));

                    b.HasKey("Id");

                    b.HasIndex("JitenDeckId");

                    b.HasIndex("JitenSubdeckId");

                    b.HasIndex("MediaInstallmentId");

                    b.HasIndex("MediaSeriesId");

                    b.ToTable("MediaWorks", t =>
                        {
                            t.HasCheckConstraint("CK_MediaWorks_CoverProviderItemId", "(\"CoverSource\" IN (5, 6) AND \"CoverProviderItemId\" IS NOT NULL) OR (\"CoverSource\" NOT IN (5, 6) AND \"CoverProviderItemId\" IS NULL)");

                            t.HasCheckConstraint("CK_MediaWorks_CoverUrlAndSource", "(\"CoverUrl\" IS NULL AND \"CoverSource\" = 0) OR (\"CoverUrl\" IS NOT NULL AND \"CoverSource\" <> 0)");

                            t.HasCheckConstraint("CK_MediaWorks_JitenSubdeckRequiresDeck", "\"JitenSubdeckId\" IS NULL OR \"JitenDeckId\" IS NOT NULL");

                            t.HasCheckConstraint("CK_MediaWorks_TtsuCharacterCount", "\"TtsuCharacterCount\" IS NULL OR \"TtsuCharacterCount\" > 0");
                        });
                });

            modelBuilder.Entity("Kiseki.Core.Entities.TtsuBinding", b =>
                {
                    b.Property<Guid>("MediaWorkId")
                        .HasColumnType("uuid");

                    b.Property<int?>("CurrentCharacterPosition")
                        .HasColumnType("integer");

                    b.Property<string>("FolderHint")
                        .HasColumnType("text");

                    b.Property<string>("OriginalTitle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ProgressDatabaseVersion")
                        .HasColumnType("integer");

                    b.Property<int?>("ProgressExporterVersion")
                        .HasColumnType("integer");

                    b.Property<double?>("ProgressFraction")
                        .HasColumnType("double precision");

                    b.Property<long?>("ProgressRevision")
                        .HasColumnType("bigint");

                    b.Property<int?>("TotalInferenceKind")
                        .HasColumnType("integer");

                    b.Property<Guid>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.HasKey("MediaWorkId");

                    b.ToTable("TtsuBindings", t =>
                        {
                            t.HasCheckConstraint("CK_TtsuBindings_CurrentCharacterPosition", "\"CurrentCharacterPosition\" IS NULL OR \"CurrentCharacterPosition\" >= 0");

                            t.HasCheckConstraint("CK_TtsuBindings_ProgressFraction", "\"ProgressFraction\" IS NULL OR (\"ProgressFraction\" >= 0 AND \"ProgressFraction\" <= 1)");

                            t.HasCheckConstraint("CK_TtsuBindings_ProgressRevision", "\"ProgressRevision\" IS NULL OR \"ProgressRevision\" >= 0");
                        });
                });

            modelBuilder.Entity("Kiseki.Core.Entities.TtsuImportReceipt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AddedDays")
                        .HasColumnType("integer");

                    b.Property<int>("Books")
                        .HasColumnType("integer");

                    b.Property<int>("CharacterTotalUpdates")
                        .HasColumnType("integer");

                    b.Property<int>("MetadataLinks")
                        .HasColumnType("integer");

                    b.Property<int>("MetadataSkips")
                        .HasColumnType("integer");

                    b.Property<int>("ProgressUpdates")
                        .HasColumnType("integer");

                    b.Property<int>("StaleDays")
                        .HasColumnType("integer");

                    b.Property<int>("UnchangedDays")
                        .HasColumnType("integer");

                    b.Property<int>("UpdatedDays")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("TtsuImportReceipts");
                });

            modelBuilder.Entity("Kiseki.Core.Entities.ImmersionLog", b =>
                {
                    b.HasOne("Kiseki.Core.Entities.MediaWork", null)
                        .WithMany("Logs")
                        .HasForeignKey("MediaWorkId");

                    b.HasOne("Kiseki.Core.Entities.TtsuBinding", null)
                        .WithMany()
                        .HasForeignKey("TtsuBindingId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Kiseki.Core.Entities.InstallmentProviderIdentity", b =>
                {
                    b.HasOne("Kiseki.Core.Entities.MediaInstallment", "MediaInstallment")
                        .WithMany("ProviderIdentities")
                        .HasForeignKey("MediaInstallmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MediaInstallment");
                });

            modelBuilder.Entity("Kiseki.Core.Entities.InstallmentProviderSnapshot", b =>
                {
                    b.HasOne("Kiseki.Core.Entities.InstallmentProviderIdentity", "ProviderIdentity")
                        .WithMany("Snapshots")
                        .HasForeignKey("Provider", "NormalizedKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProviderIdentity");
                });

            modelBuilder.Entity("Kiseki.Core.Entities.MediaInstallment", b =>
                {
                    b.HasOne("Kiseki.Core.Entities.MediaSeries", "MediaSeries")
                        .WithMany("Installments")
                        .HasForeignKey("MediaSeriesId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("MediaSeries");
                });

            modelBuilder.Entity("Kiseki.Core.Entities.MediaSeries", b =>
                {
                    b.HasOne("Kiseki.Core.Entities.Franchise", "Franchise")
                        .WithMany("Series")
                        .HasForeignKey("FranchiseId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Franchise");
                });

            modelBuilder.Entity("Kiseki.Core.Entities.MediaWork", b =>
                {
                    b.HasOne("Kiseki.Core.Entities.MediaInstallment", "MediaInstallment")
                        .WithMany("Copies")
                        .HasForeignKey("MediaInstallmentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Kiseki.Core.Entities.MediaSeries", "MediaSeries")
                        .WithMany("Works")
                        .HasForeignKey("MediaSeriesId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("MediaInstallment");

                    b.Navigation("MediaSeries");
                });

            modelBuilder.Entity("Kiseki.Core.Entities.TtsuBinding", b =>
                {
                    b.HasOne("Kiseki.Core.Entities.MediaWork", null)
                        .WithOne()
                        .HasForeignKey("Kiseki.Core.Entities.TtsuBinding", "MediaWorkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Kiseki.Core.Entities.Franchise", b =>
                {
                    b.Navigation("Series");
                });

            modelBuilder.Entity("Kiseki.Core.Entities.InstallmentProviderIdentity", b =>
                {
                    b.Navigation("Snapshots");
                });

            modelBuilder.Entity("Kiseki.Core.Entities.MediaInstallment", b =>
                {
                    b.Navigation("Copies");

                    b.Navigation("ProviderIdentities");
                });

            modelBuilder.Entity("Kiseki.Core.Entities.MediaSeries", b =>
                {
                    b.Navigation("Installments");

                    b.Navigation("Works");
                });

            modelBuilder.Entity("Kiseki.Core.Entities.MediaWork", b =>
                {
                    b.Navigation("Logs");
                });
#pragma warning restore 612, 618
        }
    }
}
