// <auto-generated />
using System;
using Kiseki.Core;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Kiseki.Core.Migrations
{
    [DbContext(typeof(ImmersionDbContext))]
    partial class ImmersionDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Kiseki.Core.Entities.Franchise", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("JitenAnchorDeckId")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("JitenAnchorDeckId");

                    b.ToTable("Franchises");
                });

            modelBuilder.Entity("Kiseki.Core.Entities.ImmersionLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CharactersRead")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<Guid?>("MediaWorkId")
                        .HasColumnType("uuid");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("TimeSpentMinutes")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("MediaWorkId");

                    b.ToTable("ImmersionLogs");
                });

            modelBuilder.Entity("Kiseki.Core.Entities.MediaSeries", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("FranchiseId")
                        .HasColumnType("uuid");

                    b.Property<int?>("JitenDeckId")
                        .HasColumnType("integer");

                    b.Property<int>("MediaType")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FranchiseId");

                    b.HasIndex("JitenDeckId");

                    b.ToTable("MediaSeries");
                });

            modelBuilder.Entity("Kiseki.Core.Entities.MediaWork", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<int?>("JitenCharacterCount")
                        .HasColumnType("integer");

                    b.Property<string>("JitenCoverUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<int?>("JitenDeckId")
                        .HasColumnType("integer");

                    b.Property<int?>("JitenSubdeckId")
                        .HasColumnType("integer");

                    b.Property<int?>("ManualCharacterCountOverride")
                        .HasColumnType("integer");

                    b.Property<Guid?>("MediaSeriesId")
                        .HasColumnType("uuid");

                    b.Property<int>("MediaType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("JitenDeckId");

                    b.HasIndex("JitenSubdeckId");

                    b.HasIndex("MediaSeriesId");

                    b.ToTable("MediaWorks", t =>
                        {
                            t.HasCheckConstraint("CK_MediaWorks_JitenSubdeckRequiresDeck", "\"JitenSubdeckId\" IS NULL OR \"JitenDeckId\" IS NOT NULL");
                        });
                });

            modelBuilder.Entity("Kiseki.Core.Entities.ImmersionLog", b =>
                {
                    b.HasOne("Kiseki.Core.Entities.MediaWork", null)
                        .WithMany("Logs")
                        .HasForeignKey("MediaWorkId");
                });

            modelBuilder.Entity("Kiseki.Core.Entities.MediaSeries", b =>
                {
                    b.HasOne("Kiseki.Core.Entities.Franchise", "Franchise")
                        .WithMany("Series")
                        .HasForeignKey("FranchiseId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Franchise");
                });

            modelBuilder.Entity("Kiseki.Core.Entities.MediaWork", b =>
                {
                    b.HasOne("Kiseki.Core.Entities.MediaSeries", "MediaSeries")
                        .WithMany("Works")
                        .HasForeignKey("MediaSeriesId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("MediaSeries");
                });

            modelBuilder.Entity("Kiseki.Core.Entities.Franchise", b =>
                {
                    b.Navigation("Series");
                });

            modelBuilder.Entity("Kiseki.Core.Entities.MediaSeries", b =>
                {
                    b.Navigation("Works");
                });

            modelBuilder.Entity("Kiseki.Core.Entities.MediaWork", b =>
                {
                    b.Navigation("Logs");
                });
#pragma warning restore 612, 618
        }
    }
}
