// <auto-generated />
using System;
using Kiseki.Core;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Kiseki.Core.Migrations
{
    [DbContext(typeof(ImmersionDbContext))]
    partial class ImmersionDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Kiseki.Core.Entities.Franchise", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("JitenAnchorDeckId")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("JitenAnchorDeckId");

                    b.ToTable("Franchises");
                });

            modelBuilder.Entity("Kiseki.Core.Entities.ImmersionLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CharactersRead")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<Guid?>("MediaWorkId")
                        .HasColumnType("uuid");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long?>("SourceRevision")
                        .HasColumnType("bigint");

                    b.Property<double>("TimeSpentMinutes")
                        .HasColumnType("double precision");

                    b.Property<Guid?>("TtsuBindingId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("MediaWorkId");

                    b.HasIndex("TtsuBindingId", "Date")
                        .IsUnique();

                    b.ToTable("ImmersionLogs", t =>
                        {
                            t.HasCheckConstraint("CK_ImmersionLogs_TtsuBinding", "\"TtsuBindingId\" IS NULL OR (\"MediaWorkId\" IS NOT NULL AND \"TtsuBindingId\" = \"MediaWorkId\" AND \"Source\" = 'ttsu')");
                        });
                });

            modelBuilder.Entity("Kiseki.Core.Entities.MediaSeries", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("FranchiseId")
                        .HasColumnType("uuid");

                    b.Property<int?>("JitenDeckId")
                        .HasColumnType("integer");

                    b.Property<int>("MediaType")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FranchiseId");

                    b.HasIndex("JitenDeckId");

                    b.ToTable("MediaSeries");
                });

            modelBuilder.Entity("Kiseki.Core.Entities.MediaWork", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CoverProviderItemId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("CoverSource")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("CoverUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<int?>("JitenCharacterCount")
                        .HasColumnType("integer");

                    b.Property<int?>("JitenDeckId")
                        .HasColumnType("integer");

                    b.Property<int?>("JitenSubdeckId")
                        .HasColumnType("integer");

                    b.Property<int?>("ManualCharacterCountOverride")
                        .HasColumnType("integer");

                    b.Property<Guid?>("MediaSeriesId")
                        .HasColumnType("uuid");

                    b.Property<int>("MediaType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("TtsuCharacterCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("JitenDeckId");

                    b.HasIndex("JitenSubdeckId");

                    b.HasIndex("MediaSeriesId");

                    b.ToTable("MediaWorks", t =>
                        {
                            t.HasCheckConstraint("CK_MediaWorks_CoverProviderItemId", "(\"CoverSource\" IN (5, 6) AND \"CoverProviderItemId\" IS NOT NULL) OR (\"CoverSource\" NOT IN (5, 6) AND \"CoverProviderItemId\" IS NULL)");

                            t.HasCheckConstraint("CK_MediaWorks_CoverUrlAndSource", "(\"CoverUrl\" IS NULL AND \"CoverSource\" = 0) OR (\"CoverUrl\" IS NOT NULL AND \"CoverSource\" <> 0)");

                            t.HasCheckConstraint("CK_MediaWorks_JitenSubdeckRequiresDeck", "\"JitenSubdeckId\" IS NULL OR \"JitenDeckId\" IS NOT NULL");

                            t.HasCheckConstraint("CK_MediaWorks_TtsuCharacterCount", "\"TtsuCharacterCount\" IS NULL OR \"TtsuCharacterCount\" > 0");
                        });
                });

            modelBuilder.Entity("Kiseki.Core.Entities.TtsuBinding", b =>
                {
                    b.Property<Guid>("MediaWorkId")
                        .HasColumnType("uuid");

                    b.Property<int?>("CurrentCharacterPosition")
                        .HasColumnType("integer");

                    b.Property<string>("FolderHint")
                        .HasColumnType("text");

                    b.Property<string>("OriginalTitle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ProgressDatabaseVersion")
                        .HasColumnType("integer");

                    b.Property<int?>("ProgressExporterVersion")
                        .HasColumnType("integer");

                    b.Property<double?>("ProgressFraction")
                        .HasColumnType("double precision");

                    b.Property<long?>("ProgressRevision")
                        .HasColumnType("bigint");

                    b.Property<int?>("TotalInferenceKind")
                        .HasColumnType("integer");

                    b.Property<Guid>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.HasKey("MediaWorkId");

                    b.ToTable("TtsuBindings", t =>
                        {
                            t.HasCheckConstraint("CK_TtsuBindings_CurrentCharacterPosition", "\"CurrentCharacterPosition\" IS NULL OR \"CurrentCharacterPosition\" >= 0");

                            t.HasCheckConstraint("CK_TtsuBindings_ProgressFraction", "\"ProgressFraction\" IS NULL OR (\"ProgressFraction\" >= 0 AND \"ProgressFraction\" <= 1)");

                            t.HasCheckConstraint("CK_TtsuBindings_ProgressRevision", "\"ProgressRevision\" IS NULL OR \"ProgressRevision\" >= 0");
                        });
                });

            modelBuilder.Entity("Kiseki.Core.Entities.TtsuImportReceipt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AddedDays")
                        .HasColumnType("integer");

                    b.Property<int>("Books")
                        .HasColumnType("integer");

                    b.Property<int>("CharacterTotalUpdates")
                        .HasColumnType("integer");

                    b.Property<int>("MetadataLinks")
                        .HasColumnType("integer");

                    b.Property<int>("MetadataSkips")
                        .HasColumnType("integer");

                    b.Property<int>("ProgressUpdates")
                        .HasColumnType("integer");

                    b.Property<int>("StaleDays")
                        .HasColumnType("integer");

                    b.Property<int>("UnchangedDays")
                        .HasColumnType("integer");

                    b.Property<int>("UpdatedDays")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("TtsuImportReceipts");
                });

            modelBuilder.Entity("Kiseki.Core.Entities.ImmersionLog", b =>
                {
                    b.HasOne("Kiseki.Core.Entities.MediaWork", null)
                        .WithMany("Logs")
                        .HasForeignKey("MediaWorkId");

                    b.HasOne("Kiseki.Core.Entities.TtsuBinding", null)
                        .WithMany()
                        .HasForeignKey("TtsuBindingId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Kiseki.Core.Entities.MediaSeries", b =>
                {
                    b.HasOne("Kiseki.Core.Entities.Franchise", "Franchise")
                        .WithMany("Series")
                        .HasForeignKey("FranchiseId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Franchise");
                });

            modelBuilder.Entity("Kiseki.Core.Entities.MediaWork", b =>
                {
                    b.HasOne("Kiseki.Core.Entities.MediaSeries", "MediaSeries")
                        .WithMany("Works")
                        .HasForeignKey("MediaSeriesId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("MediaSeries");
                });

            modelBuilder.Entity("Kiseki.Core.Entities.TtsuBinding", b =>
                {
                    b.HasOne("Kiseki.Core.Entities.MediaWork", null)
                        .WithOne()
                        .HasForeignKey("Kiseki.Core.Entities.TtsuBinding", "MediaWorkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Kiseki.Core.Entities.Franchise", b =>
                {
                    b.Navigation("Series");
                });

            modelBuilder.Entity("Kiseki.Core.Entities.MediaSeries", b =>
                {
                    b.Navigation("Works");
                });

            modelBuilder.Entity("Kiseki.Core.Entities.MediaWork", b =>
                {
                    b.Navigation("Logs");
                });
#pragma warning restore 612, 618
        }
    }
}
